/** The graph engine is packaged in app.js; no CDN, API call, or remote layout. */
export const cytoscapeCareerGraphStyles = `.graph-shell{position:relative;padding:12px;border:1px solid var(--line);border-radius:9px;background:var(--surface)}.graph-toolbar{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;flex-wrap:wrap;margin:0 0 12px}.graph-focus-picker{position:relative;flex:1;min-width:min(100%,300px)}.graph-focus-picker label{display:block;margin-bottom:5px;font-size:11px;font-weight:700;color:var(--muted)}.graph-focus-picker input{width:100%;height:36px;padding:0 11px;border:1px solid var(--line);border-radius:6px;background:#fff}.graph-focus-options{position:absolute;top:60px;left:0;z-index:8;width:min(100%,440px);max-height:280px;overflow:auto;padding:5px;border:1px solid var(--line);border-radius:6px;background:var(--surface);box-shadow:var(--shadow)}.graph-focus-options[hidden]{display:none}.graph-focus-options button{display:flex;width:100%;align-items:center;justify-content:space-between;gap:8px;padding:8px;border:0;border-radius:4px;background:transparent;text-align:left;cursor:pointer}.graph-focus-options button:hover,.graph-focus-options button:focus-visible{background:var(--blue-soft)}.graph-focus-options button[aria-selected=true]{color:var(--blue)}.graph-focus-options small{color:var(--muted)}.graph-focus-chips{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.graph-focus-chips button{padding:4px 7px;border:1px solid #cbd9e4;border-radius:5px;background:#f6f9fc;font-size:11px;cursor:pointer}.graph-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.graph-actions button{min-height:36px;padding:6px 10px;border:1px solid var(--line);border-radius:5px;background:var(--surface);cursor:pointer}.graph-actions button:hover{border-color:var(--blue)}.graph-layout{grid-template-columns:minmax(0,1fr) minmax(330px,390px);gap:12px}.graph-wrap{height:clamp(440px,58svh,620px);min-height:0;overflow:hidden;background:radial-gradient(circle at 35% 24%,#f3f9fc 0,transparent 55%),radial-gradient(circle at 74% 78%,#f4f9f5 0,transparent 50%),#fcfdfe}.graph{display:block;min-width:0;width:100%;height:100%;touch-action:none}.graph-shell #graph-inspector{top:0;max-height:clamp(440px,58svh,620px);overflow:auto}.graph-keyboard{margin:12px 0 0;font-size:12px;color:var(--muted)}.graph-keyboard summary{cursor:pointer}.graph-keyboard .tools{position:static;display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}.graph-keyboard select{max-width:100%;height:36px;padding:0 8px;border:1px solid var(--line);border-radius:5px;background:#fff}.graph-keyboard button{min-height:36px;padding:6px 10px;border:1px solid var(--line);border-radius:5px;background:#fff;cursor:pointer}@media(max-width:820px){.graph-layout{grid-template-columns:1fr}.graph-wrap{height:clamp(380px,54svh,520px)}.graph-shell #graph-inspector{max-height:min(78svh,680px)}}@media print{.graph-shell{display:none!important}}`;

export const cytoscapeCareerGraphLegendStyles = `.graph-legend{display:flex;gap:6px 14px;align-items:center;flex-wrap:wrap;margin:0 0 12px;color:var(--muted);font-size:11px}.graph-legend span{display:inline-flex;align-items:center;gap:5px}.graph-legend i{display:inline-block;width:10px;height:10px;border:1px solid #5d6972;border-radius:50%}.graph-legend [data-legend-type=Person]{background:#4f6d7a}.graph-legend [data-legend-type=Organisation]{background:#73a8e8}.graph-legend [data-legend-type=Engagement]{background:#63c7b2}.graph-legend [data-legend-type=Role]{background:#8d96c9}.graph-legend [data-legend-type=Work]{background:#e6b85c}.graph-legend [data-legend-type=Contribution]{background:#6dc6d9}.graph-legend [data-legend-type=Technology]{background:#ed8b5a}.graph-legend [data-legend-type=TechnologyUse]{background:#b584cc}.graph-legend [data-legend-type=TechnologyCategory]{background:#e66e68}.graph-legend [data-legend-type=ReportedOutcome]{background:#d77bb5}.graph-legend [data-legend-type=Credential]{background:#b99a45}.graph-legend [data-legend-type=Publication]{background:#7165a5}.graph-legend [data-legend-type=ReferenceLink]{background:#479f91}`;

/** Appended after the shared entity/expertise app. Its only edges are model.relations. */
export const cytoscapeCareerGraphApp = String.raw`
const graph=document.querySelector("#graph"),focus=document.querySelector("#graph-focus"),focusOptions=document.querySelector("#graph-focus-options"),focusChips=document.querySelector("#graph-focus-chips"),focusClear=document.querySelector("#graph-focus-clear"),graphFit=document.querySelector("#graph-fit"),graphExpand=document.querySelector("#graph-expand"),graphShell=document.querySelector("#graph-shell"),graphPanel=document.querySelector("#graph-inspector"),keyboardNode=document.querySelector("#graph-keyboard-node"),keyboardRead=document.querySelector("#graph-keyboard-read"),keyboardExplore=document.querySelector("#graph-keyboard-explore");
if(typeof cytoscape!=="function")throw new Error("Packaged Cytoscape graph engine is missing");
const graphItems=[...items.values()].sort((a,b)=>a.type.localeCompare(b.type)||a.name.localeCompare(b.name)||a.id.localeCompare(b.id)),graphIds=new Set(graphItems.map(item=>item.id));
const graphRelations=relations.filter(relation=>graphIds.has(relation.subject)&&graphIds.has(relation.object));
const graphAdj=new Map(graphItems.map(item=>[item.id,new Set([item.id])]));
graphRelations.forEach(relation=>{graphAdj.get(relation.subject).add(relation.object);graphAdj.get(relation.object).add(relation.subject)});
const degreeValues=graphItems.map(item=>graphAdj.get(item.id).size-1).sort((a,b)=>a-b),maxDegree=degreeValues.at(-1)||0,hubDegree=Math.max(3,degreeValues[Math.floor(degreeValues.length*.75)]||0);
const typeColour={Person:"#4F6D7A",Organisation:"#73A8E8",Engagement:"#63C7B2",Role:"#8D96C9",Work:"#E6B85C",Contribution:"#6DC6D9",TechnologyUse:"#B584CC",Technology:"#ED8B5A",TechnologyCategory:"#E66E68","Reported outcome":"#D77BB5",Credential:"#B99A45",Publication:"#7165A5","Reference link":"#479F91",Evidence:"#A5B0BA"};
const typeBorder={Person:"#263F49",Organisation:"#315F98",Engagement:"#287A6B",Role:"#545C94",Work:"#9A6A17",Contribution:"#287A8A",TechnologyUse:"#704584",Technology:"#A84E25",TechnologyCategory:"#9B3632","Reported outcome":"#8F3E70",Credential:"#745E1D",Publication:"#433778","Reference link":"#276A60",Evidence:"#5D6972"};
const legendTypes={Person:"Person",Organisation:"Organisation / company",Engagement:"Engagement",Role:"Role",Work:"Work",Contribution:"Contribution",Technology:"Technology",TechnologyUse:"Technology use",TechnologyCategory:"Category",ReportedOutcome:"Outcome",Credential:"Credential",Publication:"Publication",ReferenceLink:"Reference link"};const graphLegend=document.createElement("div");graphLegend.className="graph-legend";graphLegend.setAttribute("aria-label","Entity colour legend");graphLegend.innerHTML=Object.entries(legendTypes).map(([type,label])=>'<span><i aria-hidden="true" data-legend-type="'+type+'"></i>'+label+'</span>').join("");graphShell.insertBefore(graphLegend,graphShell.firstChild);
const anchorTypes=new Set(["Organisation","Engagement","Role","Work","TechnologyCategory"]),anchors=new Set();
for(const type of new Set(graphItems.map(item=>item.type))){const candidates=graphItems.filter(item=>item.type===type).sort((a,b)=>(graphAdj.get(b.id).size-graphAdj.get(a.id).size)||a.name.localeCompare(b.name));if(candidates[0]&&anchorTypes.has(type))anchors.add(candidates[0].id)}
const graphElements=[...graphItems.map(item=>({data:{id:item.id,name:item.name,type:item.type,degree:graphAdj.get(item.id).size-1,featured:item.inclusion?.status==="featured"},classes:[anchors.has(item.id)?"label-anchor":"",item.type==="TechnologyCategory"?"category-hub":""].filter(Boolean).join(" ")})),...graphRelations.map(relation=>({data:{id:"relation:"+relation.id,source:relation.subject,target:relation.object,predicate:relation.predicate}}))];
function nodeSize(ele){const degree=Math.max(0,Number(ele.data("degree"))||0),growth=maxDegree?Math.log1p(degree)/Math.log1p(maxDegree):0,type=ele.data("type"),minimum=type==="TechnologyCategory"?30:anchorTypes.has(type)?24:18,maximum=type==="TechnologyCategory"?62:anchorTypes.has(type)?54:46;return Math.round(minimum+(maximum-minimum)*growth)}
const cy=cytoscape({container:graph,elements:graphElements,wheelSensitivity:.18,minZoom:.12,maxZoom:4,boxSelectionEnabled:false,autoungrabify:false,style:[
 {selector:"node",style:{"background-color":ele=>typeColour[ele.data("type")]||"#edf1f5","border-width":1.4,"border-color":ele=>typeBorder[ele.data("type")]||"#7d91a3",shape:"ellipse",width:nodeSize,height:nodeSize,label:"",color:"#25394b","font-size":11,"font-weight":600,"text-valign":"bottom","text-margin-y":7,"text-background-color":"#ffffff","text-background-opacity":.92,"text-background-padding":2,"text-background-shape":"roundrectangle","z-index":3}},
 {selector:"node.label-anchor",style:{label:"data(name)","font-size":12,"font-weight":700}},
 {selector:"node.category-hub",style:{label:"data(name)","border-color":"#987a35","border-width":2.2,"font-size":12,"font-weight":700}},
 {selector:"node.is-labelled",style:{label:"data(name)","text-max-width":200,"text-wrap":"wrap"}},
 {selector:"node.is-neighbour",style:{"border-color":"#26735c","border-width":2.5}},
 {selector:"node.is-selected,node.is-focused",style:{"border-color":"#1769aa","border-width":3,"background-color":"#d7eafa","z-index":10}},
 {selector:"node.is-quiet",style:{opacity:.15}},
 {selector:"edge",style:{width:1.15,"line-color":"#a9bdca","curve-style":"bezier",opacity:.105,"z-index":1}},
 {selector:"edge.is-connected",style:{width:1.8,"line-color":"#729cb9",opacity:.72,"z-index":2}},
 {selector:"edge.is-quiet",style:{opacity:.018}}
],layout:{name:"cose",animate:false,fit:true,padding:70,idealEdgeLength:ele=>ele.source().data("type")===ele.target().data("type")?92:135,nodeRepulsion:ele=>ele.data("degree")>12?180000:105000,edgeElasticity:90,nestingFactor:1.35,numIter:1500,randomize:false,componentSpacing:150,gravity:.12}});
let selectedNode=null,hoverNode=null,clickedFocus=null,focusIds=new Set(),expanded=false,pressTimer=null;
function activeRoots(){return focusIds.size?focusIds:clickedFocus?new Set([clickedFocus]):new Set()}
function activeNeighbours(){const roots=activeRoots();if(!roots.size)return null;const shown=new Set();for(const id of roots)for(const neighbour of graphAdj.get(id)||[])shown.add(neighbour);return shown}
function graphCollection(ids){const nodes=cy.collection();for(const id of ids){const node=cy.getElementById(id);if(node.length)nodes.merge(node)}return nodes}
function highlightGraph(){const roots=activeRoots(),near=activeNeighbours(),selectedNeighbours=new Set(graphAdj.get(selectedNode)||[]),visible=expanded&&selectedNode?selectedNeighbours:null;cy.batch(()=>{cy.nodes().forEach(node=>{const id=node.id(),quiet=(!!near&&!near.has(id))||(!!visible&&!visible.has(id));node.toggleClass("is-quiet",quiet);node.toggleClass("is-focused",focusIds.has(id)||clickedFocus===id);node.toggleClass("is-selected",selectedNode===id);node.toggleClass("is-neighbour",selectedNeighbours.has(id)&&id!==selectedNode);node.toggleClass("is-labelled",!!near&&near.has(id)||hoverNode===id)});cy.edges().forEach(edge=>{const source=edge.source().id(),target=edge.target().id(),connected=roots.size?(roots.has(source)||roots.has(target)):selectedNode&&(source===selectedNode||target===selectedNode),quiet=(!!near&&!connected)||(!!visible&&!connected);edge.toggleClass("is-connected",!!connected);edge.toggleClass("is-quiet",quiet)})})}
function overviewCollection(){return cy.nodes().filter(node=>node.hasClass("category-hub")||["Organisation","Engagement"].includes(node.data("type"))||node.data("degree")>=hubDegree)}
function fitGraph(collection=overviewCollection(),padding=80,minZoom=window.matchMedia("(max-width: 820px)").matches ? .32 : .46){if(!collection.length)return;const finish=()=>{if(cy.zoom()<minZoom){cy.zoom(minZoom);cy.center(collection)}};if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){cy.fit(collection,padding);finish()}else cy.animate({fit:{eles:collection,padding}},{duration:360,complete:finish})}
function readNode(id,trigger,makeClickFocus=false){const item=items.get(id);if(!item)return;selectedNode=id;expanded=false;graphExpand.disabled=false;graphExpand.textContent="Expand neighbours";if(makeClickFocus&&!focusIds.size){clickedFocus=id;renderFocusChips()}const count=graphAdj.get(id).size-1;graphPanel.dataset.selectedId=id;graphPanel.innerHTML='<p class="overline">Selected node · '+esc(item.type)+'</p><h3>'+entity(id,item.name)+'</h3><p class="focused-summary">'+esc(item.summary||"No entity-specific narrative is present; explore linked records for context.")+'</p>'+(item.details.length?'<dl>'+item.details.map(detail=>'<div><dt>'+esc(detail.label)+'</dt><dd>'+esc(detail.value)+'</dd></div>').join("")+'</dl>':"")+'<p class="meta">'+count+' connected '+(count===1?'record':'records')+'</p><div class="connections">'+(connections(id)||'<p>No explicit relationships connect this node.</p>')+'</div>';const framed=focusIds.size>1?activeNeighbours():graphAdj.get(id);highlightGraph();fitGraph(graphCollection(framed),95,focusIds.size>1?.46:.58);graphPanel.dispatchEvent(new CustomEvent("graph-selection-change",{bubbles:true,detail:{id,trigger}}))}
function renderFocusChips(){focusChips.innerHTML=[...focusIds].map(id=>'<button type="button" data-remove-focus="'+esc(id)+'" aria-label="Remove '+esc(items.get(id).name)+' from focus">'+esc(items.get(id).name)+' ×</button>').join("");focusClear.disabled=!focusIds.size&&!clickedFocus;renderFocusOptions()}
function renderFocusOptions(){const query=focus.value.toLowerCase().trim(),matches=graphItems.filter(item=>!query||item.name.toLowerCase().includes(query)||item.id.toLowerCase().includes(query)||item.type.toLowerCase().includes(query));focusOptions.innerHTML=matches.map(item=>'<button type="button" role="option" aria-selected="'+focusIds.has(item.id)+'" data-focus-option="'+esc(item.id)+'"><span>'+esc(item.name)+'</span><small>'+esc(item.type)+'</small></button>').join("")||'<p>No matching career records.</p>';focusOptions.hidden=document.activeElement!==focus&&!focusOptions.contains(document.activeElement);focus.setAttribute("aria-expanded",String(!focusOptions.hidden))}
function addFocus(id,trigger){if(!items.has(id))return;focusIds.add(id);clickedFocus=null;renderFocusChips();readNode(id,trigger||focus,false)}
function toggleFocus(id,trigger){if(focusIds.has(id)){focusIds.delete(id);clickedFocus=null;renderFocusChips();highlightGraph()}else addFocus(id,trigger);focus.value="";renderFocusOptions();if(!window.matchMedia("(max-width: 820px)").matches)focus.focus()}
function clearFocus(){focusIds.clear();clickedFocus=null;expanded=false;graphExpand.textContent="Expand neighbours";renderFocusChips();highlightGraph()}
focus.addEventListener("focus",()=>{focusOptions.hidden=false;focus.setAttribute("aria-expanded","true");renderFocusOptions()});focus.addEventListener("input",()=>{focusOptions.hidden=false;renderFocusOptions()});focus.addEventListener("keydown",event=>{if(event.key==="Escape"){focusOptions.hidden=true;focus.setAttribute("aria-expanded","false");return}if(event.key==="ArrowDown"){event.preventDefault();focusOptions.querySelector("[data-focus-option]")?.focus()}if(event.key==="Enter"){const first=focusOptions.querySelector("[data-focus-option]");if(first){event.preventDefault();toggleFocus(first.dataset.focusOption,focus)}}});
focusOptions.addEventListener("click",event=>{const option=event.target.closest("[data-focus-option]");if(option)toggleFocus(option.dataset.focusOption,option)});focusOptions.addEventListener("keydown",event=>{if(event.key==="Escape"){focusOptions.hidden=true;focus.setAttribute("aria-expanded","false");focus.focus()}else if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();const options=[...focusOptions.querySelectorAll("[data-focus-option]")],current=options.indexOf(document.activeElement),next=options[Math.max(0,Math.min(options.length-1,current+(event.key==="ArrowDown"?1:-1)))];next?.focus()}});
focusChips.addEventListener("click",event=>{const remove=event.target.closest("[data-remove-focus]");if(remove){focusIds.delete(remove.dataset.removeFocus);clickedFocus=null;renderFocusChips();highlightGraph();focus.focus()}});focusClear.addEventListener("click",clearFocus);document.addEventListener("click",event=>{if(!event.target.closest(".graph-focus-picker")){focusOptions.hidden=true;focus.setAttribute("aria-expanded","false")}});
graphFit.addEventListener("click",()=>{expanded=false;selectedNode=null;clickedFocus=null;focusIds.clear();delete graphPanel.dataset.selectedId;graphPanel.innerHTML='<p class="overline">Career graph</p><h3>Select a node</h3><p>All '+graphItems.length+' authorised records and '+graphRelations.length+' explicit relationships are present. Hover for a name; click to reveal every directly connected node label, then expand or explore.</p>';graphExpand.textContent="Expand neighbours";graphExpand.disabled=true;renderFocusChips();highlightGraph();fitGraph(overviewCollection(),80)});graphExpand.addEventListener("click",()=>{if(!selectedNode)return;expanded=!expanded;graphExpand.textContent=expanded?"Return to overview":"Expand neighbours";highlightGraph();fitGraph(expanded?graphCollection(graphAdj.get(selectedNode)):overviewCollection(),expanded?95:80,expanded ? .58 : .46)});
function exploreGraphNode(id){open(id)}
cy.on("tap","node",event=>readNode(event.target.id(),graph,true));cy.on("mouseover","node",event=>{hoverNode=event.target.id();highlightGraph()});cy.on("mouseout","node",event=>{if(hoverNode===event.target.id()){hoverNode=null;highlightGraph()}});
cy.on("dbltap","node",event=>exploreGraphNode(event.target.id()));cy.on("cxttap","node",event=>exploreGraphNode(event.target.id()));
cy.on("taphold","node",event=>exploreGraphNode(event.target.id()));
keyboardNode.innerHTML=graphItems.map(item=>'<option value="'+esc(item.id)+'">'+esc(item.name)+' · '+esc(item.type)+'</option>').join("");keyboardRead.addEventListener("click",()=>readNode(keyboardNode.value,keyboardRead,true));keyboardExplore.addEventListener("click",()=>exploreGraphNode(keyboardNode.value));
document.addEventListener("click",event=>{const control=event.target.closest("[data-focus-graph]");if(!control)return;const id=control.dataset.focusGraph;close();setView("graph-view");addFocus(id,control);history.replaceState(null,"","#graph-view")});
document.querySelector("#evidence-search").addEventListener("input",event=>document.querySelectorAll("#evidence-body tr").forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(event.target.value.toLowerCase())));
graphPanel.innerHTML='<p class="overline">Career graph</p><h3>Select a node</h3><p>All '+graphItems.length+' authorised records and '+graphRelations.length+' explicit relationships are present. Hover for a name; click to reveal every directly connected node label, then expand or explore.</p>';graphExpand.disabled=true;renderFocusChips();
if("ResizeObserver" in window)new ResizeObserver(()=>cy.resize()).observe(graph);document.querySelector("[data-tab=graph-view]")?.addEventListener("click",()=>{cy.resize();fitGraph(overviewCollection(),80)});
`;
